ci: test dedupe check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,11 +10,23 @@ jobs:
           node-version-file: '.nvmrc'
           cache: 'npm'
       - run: npm ci
+      # - name: Check for duplicate dependencies
+      #   run: |
+      #     npm dedugit ppe
+      #     git diff --exit-code package-lock.json || {
+      #       echo "::error file=package-lock.json::Lockfile changes detected after deduplication. Run 'npm dedupe' and commit the result.";
+      #       exit 1;
+      #     }
       - name: Check for duplicate dependencies
         run: |
-          npm dedupe
-          git diff --exit-code package-lock.json || {
-            echo "::error file=package-lock.json::Lockfile changes detected after deduplication. Run 'npm dedupe' and commit the result.";
-            exit 1;
-          }
+          if git diff --name-only origin/${{ github.base_ref }} | grep -q '^package-lock\.json$'; then
+            echo "package-lock.json changed, running deduplication check..."
+            npm dedupe
+            git diff --exit-code package-lock.json || {
+              echo "::error file=package-lock.json::Lockfile changes detected after deduplication. run 'npm dedupe' and commit the result.";
+              exit 1;
+            }
+          else
+            echo "package-lock.json not changed. Skipping dedupe check."
+          fi
       - run: npm test
